"""init_full_schema

Revision ID: 3bf536136255
Revises: 
Create Date: 2026-05-08 12:04:08.419206
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3bf536136255'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('person_type', sa.Enum('student', 'staff', name='person_type_enum'), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('angle', sa.Enum('face', 'left', 'right', 'up', 'down', name='face_angle_enum'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_is_active'), 'face_embeddings', ['is_active'], unique=False)
    op.create_index('ix_face_embeddings_person', 'face_embeddings', ['person_id', 'person_type'], unique=False)
    op.create_index(op.f('ix_face_embeddings_person_id'), 'face_embeddings', ['person_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_person_type'), 'face_embeddings', ['person_type'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('directeur', 'enseignant', 'secretaire', 'parent', 'eleve', name='user_role_enum'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'success', 'warning', 'error', 'attendance', 'grade', 'payment', 'bulletin', name='notification_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='notification_priority_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('enseignant', 'secretaire', 'vie_scolaire', 'technique', name='staff_role_enum'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'vacataire', name='contract_type_enum'), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('diploma', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_employee_number'), 'staff', ['employee_number'], unique=True)
    op.create_index(op.f('ix_staff_is_active'), 'staff', ['is_active'], unique=False)
    op.create_index(op.f('ix_staff_last_name'), 'staff', ['last_name'], unique=False)
    op.create_index(op.f('ix_staff_role'), 'staff', ['role'], unique=False)
    op.create_table('classrooms',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('CP', 'CE1', 'CE2', 'CM1', 'CM2', '6e', '5e', '4e', '3e', '2nde', '1ere', 'Term', name='education_level_enum'), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('head_teacher_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['head_teacher_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_academic_year'), 'classrooms', ['academic_year'], unique=False)
    op.create_index(op.f('ix_classrooms_level'), 'classrooms', ['level'], unique=False)
    op.create_index(op.f('ix_classrooms_name'), 'classrooms', ['name'], unique=False)
    op.create_table('schedules',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_academic_year'), 'schedules', ['academic_year'], unique=False)
    op.create_index(op.f('ix_schedules_classroom_id'), 'schedules', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_schedules_day_of_week'), 'schedules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_schedules_staff_id'), 'schedules', ['staff_id'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('student_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('parent1_name', sa.String(length=150), nullable=True),
    sa.Column('parent1_phone', sa.String(length=20), nullable=True),
    sa.Column('parent1_email', sa.String(length=255), nullable=True),
    sa.Column('parent2_name', sa.String(length=150), nullable=True),
    sa.Column('parent2_phone', sa.String(length=20), nullable=True),
    sa.Column('parent2_email', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session', sa.Enum('matin', 'apres-midi', name='attendance_session_enum'), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'retard', 'justified', name='attendance_status_enum'), nullable=False),
    sa.Column('detection_method', sa.Enum('facial', 'manuel', 'appel', name='detection_method_enum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('justified_by', sa.String(length=150), nullable=True),
    sa.Column('justification_document_url', sa.String(length=500), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('fees',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('fee_type', sa.Enum('scolarite', 'transport', 'cantine', 'activite', name='fee_type_enum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', 'overdue', name='fee_status_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('especes', 'virement', 'cheque', 'carte', name='payment_method_enum'), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_fees_academic_year'), 'fees', ['academic_year'], unique=False)
    op.create_index(op.f('ix_fees_due_date'), 'fees', ['due_date'], unique=False)
    op.create_index(op.f('ix_fees_status'), 'fees', ['status'], unique=False)
    op.create_index(op.f('ix_fees_student_id'), 'fees', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('classroom_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('grade_type', sa.Enum('devoir', 'examen', 'oral', 'tp', 'projet', name='grade_type_enum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_academic_year'), 'grades', ['academic_year'], unique=False)
    op.create_index(op.f('ix_grades_classroom_id'), 'grades', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_grades_date'), 'grades', ['date'], unique=False)
    op.create_index(op.f('ix_grades_semester'), 'grades', ['semester'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_subject_id'), 'grades', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_subject_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_semester'), table_name='grades')
    op.drop_index(op.f('ix_grades_date'), table_name='grades')
    op.drop_index(op.f('ix_grades_classroom_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_academic_year'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_fees_student_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_status'), table_name='fees')
    op.drop_index(op.f('ix_fees_due_date'), table_name='fees')
    op.drop_index(op.f('ix_fees_academic_year'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_schedules_staff_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_day_of_week'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_classroom_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_academic_year'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_classrooms_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_level'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_academic_year'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_staff_role'), table_name='staff')
    op.drop_index(op.f('ix_staff_last_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_is_active'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_number'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_face_embeddings_person_type'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_person_id'), table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_person', table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_is_active'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
